version: '3'
services:
  amazing-db:
    container_name: amazing-db
    hostname: amazing-db
    image: postgres:latest
    environment:
    - POSTGRES_PASSWORD=postgres123
    ports:
    - "5432:5432"

  amazing-rs:
    container_name: amazing-rs
    hostname: amazing-rs
    image: amazing/amazing-rs:latest
    depends_on:
    - amazing-db
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://amazing-db:5432/postgres
    ports:
    - "8080:8080"
