version: '3'
services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:latest
    ports:
    - "5432:5432"

  amazing-rs:
    container_name: amazing/amazing-rs
    hostname: amazing-rs
    image: amazing/amazing-rs:latest
    restart: always
    depends_on:
    - postgres
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
    ports:
    - "8080:8080"
